### ISSUE TITLE
add public mycelium peers

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/zos-config#10]
a bunch of [public mycelium peers have been setup](https://github.com/threefoldtech/tf_operations/issues/2307) and are ready for usage.

https://github.com/threefoldtech/mycelium?tab=readme-ov-file#hosted-public-nodes

**Comment by LeeSmet** [comment]
Small addition: the current configured peers will either be removed eventually or kept around for experimentation purposes. for now, they have been connected to the new peers to allow graceful migration
